//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManager.Referee.Presentation.RefereeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerListItem", Namespace="http://schemas.datacontract.org/2004/07/RefereeServiceLibrary.DTOs")]
    [System.SerializableAttribute()]
    public partial class PlayerListItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchListItem", Namespace="http://schemas.datacontract.org/2004/07/RefereeServiceLibrary.DTOs")]
    [System.SerializableAttribute()]
    public partial class MatchListItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AwayTeamGoalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AwayTeamNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HomeTeamGoalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeTeamNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AwayTeamGoals {
            get {
                return this.AwayTeamGoalsField;
            }
            set {
                if ((this.AwayTeamGoalsField.Equals(value) != true)) {
                    this.AwayTeamGoalsField = value;
                    this.RaisePropertyChanged("AwayTeamGoals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AwayTeamName {
            get {
                return this.AwayTeamNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AwayTeamNameField, value) != true)) {
                    this.AwayTeamNameField = value;
                    this.RaisePropertyChanged("AwayTeamName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HomeTeamGoals {
            get {
                return this.HomeTeamGoalsField;
            }
            set {
                if ((this.HomeTeamGoalsField.Equals(value) != true)) {
                    this.HomeTeamGoalsField = value;
                    this.RaisePropertyChanged("HomeTeamGoals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeTeamName {
            get {
                return this.HomeTeamNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeTeamNameField, value) != true)) {
                    this.HomeTeamNameField = value;
                    this.RaisePropertyChanged("HomeTeamName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchDTO", Namespace="http://schemas.datacontract.org/2004/07/RefereeServiceLibrary.DTOs")]
    [System.SerializableAttribute()]
    public partial class MatchDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AttendanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FootballManager.Referee.Presentation.RefereeService.GoalDTO[] AwayTeamGoalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AwayTeamIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AwayTeamNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FootballManager.Referee.Presentation.RefereeService.PlayerListItem[] AwayTeamPlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AwayTeamScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FootballManager.Referee.Presentation.RefereeService.GoalDTO[] HomeTeamGoalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HomeTeamIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeTeamNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FootballManager.Referee.Presentation.RefereeService.PlayerListItem[] HomeTeamPlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HomeTeamScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FootballManager.Referee.Presentation.RefereeService.RefereeDTO RefereeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FootballManager.Referee.Presentation.RefereeService.StadiumDTO StadiumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Attendance {
            get {
                return this.AttendanceField;
            }
            set {
                if ((this.AttendanceField.Equals(value) != true)) {
                    this.AttendanceField = value;
                    this.RaisePropertyChanged("Attendance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FootballManager.Referee.Presentation.RefereeService.GoalDTO[] AwayTeamGoals {
            get {
                return this.AwayTeamGoalsField;
            }
            set {
                if ((object.ReferenceEquals(this.AwayTeamGoalsField, value) != true)) {
                    this.AwayTeamGoalsField = value;
                    this.RaisePropertyChanged("AwayTeamGoals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AwayTeamId {
            get {
                return this.AwayTeamIdField;
            }
            set {
                if ((this.AwayTeamIdField.Equals(value) != true)) {
                    this.AwayTeamIdField = value;
                    this.RaisePropertyChanged("AwayTeamId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AwayTeamName {
            get {
                return this.AwayTeamNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AwayTeamNameField, value) != true)) {
                    this.AwayTeamNameField = value;
                    this.RaisePropertyChanged("AwayTeamName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FootballManager.Referee.Presentation.RefereeService.PlayerListItem[] AwayTeamPlayers {
            get {
                return this.AwayTeamPlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.AwayTeamPlayersField, value) != true)) {
                    this.AwayTeamPlayersField = value;
                    this.RaisePropertyChanged("AwayTeamPlayers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AwayTeamScore {
            get {
                return this.AwayTeamScoreField;
            }
            set {
                if ((this.AwayTeamScoreField.Equals(value) != true)) {
                    this.AwayTeamScoreField = value;
                    this.RaisePropertyChanged("AwayTeamScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FootballManager.Referee.Presentation.RefereeService.GoalDTO[] HomeTeamGoals {
            get {
                return this.HomeTeamGoalsField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeTeamGoalsField, value) != true)) {
                    this.HomeTeamGoalsField = value;
                    this.RaisePropertyChanged("HomeTeamGoals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HomeTeamId {
            get {
                return this.HomeTeamIdField;
            }
            set {
                if ((this.HomeTeamIdField.Equals(value) != true)) {
                    this.HomeTeamIdField = value;
                    this.RaisePropertyChanged("HomeTeamId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeTeamName {
            get {
                return this.HomeTeamNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeTeamNameField, value) != true)) {
                    this.HomeTeamNameField = value;
                    this.RaisePropertyChanged("HomeTeamName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FootballManager.Referee.Presentation.RefereeService.PlayerListItem[] HomeTeamPlayers {
            get {
                return this.HomeTeamPlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeTeamPlayersField, value) != true)) {
                    this.HomeTeamPlayersField = value;
                    this.RaisePropertyChanged("HomeTeamPlayers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HomeTeamScore {
            get {
                return this.HomeTeamScoreField;
            }
            set {
                if ((this.HomeTeamScoreField.Equals(value) != true)) {
                    this.HomeTeamScoreField = value;
                    this.RaisePropertyChanged("HomeTeamScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FootballManager.Referee.Presentation.RefereeService.RefereeDTO Referee {
            get {
                return this.RefereeField;
            }
            set {
                if ((object.ReferenceEquals(this.RefereeField, value) != true)) {
                    this.RefereeField = value;
                    this.RaisePropertyChanged("Referee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FootballManager.Referee.Presentation.RefereeService.StadiumDTO Stadium {
            get {
                return this.StadiumField;
            }
            set {
                if ((object.ReferenceEquals(this.StadiumField, value) != true)) {
                    this.StadiumField = value;
                    this.RaisePropertyChanged("Stadium");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RefereeDTO", Namespace="http://schemas.datacontract.org/2004/07/RefereeServiceLibrary.DTOs")]
    [System.SerializableAttribute()]
    public partial class RefereeDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StadiumDTO", Namespace="http://schemas.datacontract.org/2004/07/RefereeServiceLibrary.DTOs")]
    [System.SerializableAttribute()]
    public partial class StadiumDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FootballManager.Referee.Presentation.RefereeService.AddressDTO AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FootballManager.Referee.Presentation.RefereeService.AddressDTO Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GoalDTO", Namespace="http://schemas.datacontract.org/2004/07/RefereeServiceLibrary.DTOs")]
    [System.SerializableAttribute()]
    public partial class GoalDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FootballManager.Domain.Entity.Enums.GoalType GoalTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FootballManager.Referee.Presentation.RefereeService.PlayerListItem ScorerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeamIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FootballManager.Domain.Entity.Enums.GoalType GoalType {
            get {
                return this.GoalTypeField;
            }
            set {
                if ((this.GoalTypeField.Equals(value) != true)) {
                    this.GoalTypeField = value;
                    this.RaisePropertyChanged("GoalType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FootballManager.Referee.Presentation.RefereeService.PlayerListItem Scorer {
            get {
                return this.ScorerField;
            }
            set {
                if ((object.ReferenceEquals(this.ScorerField, value) != true)) {
                    this.ScorerField = value;
                    this.RaisePropertyChanged("Scorer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamId {
            get {
                return this.TeamIdField;
            }
            set {
                if ((this.TeamIdField.Equals(value) != true)) {
                    this.TeamIdField = value;
                    this.RaisePropertyChanged("TeamId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressDTO", Namespace="http://schemas.datacontract.org/2004/07/RefereeServiceLibrary.DTOs")]
    [System.SerializableAttribute()]
    public partial class AddressDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipcodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zipcode {
            get {
                return this.ZipcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipcodeField, value) != true)) {
                    this.ZipcodeField = value;
                    this.RaisePropertyChanged("Zipcode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RefereeService.IRefereeService")]
    public interface IRefereeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRefereeService/AuthenticateReferee", ReplyAction="http://tempuri.org/IRefereeService/AuthenticateRefereeResponse")]
        int AuthenticateReferee(string username, string password, FootballManager.Domain.Entity.Models.Authentication.Enums.UserType userType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRefereeService/AuthenticateReferee", ReplyAction="http://tempuri.org/IRefereeService/AuthenticateRefereeResponse")]
        System.Threading.Tasks.Task<int> AuthenticateRefereeAsync(string username, string password, FootballManager.Domain.Entity.Models.Authentication.Enums.UserType userType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRefereeService/ChangePassword", ReplyAction="http://tempuri.org/IRefereeService/ChangePasswordResponse")]
        bool ChangePassword(int userID, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRefereeService/ChangePassword", ReplyAction="http://tempuri.org/IRefereeService/ChangePasswordResponse")]
        System.Threading.Tasks.Task<bool> ChangePasswordAsync(int userID, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRefereeService/GetPlayer", ReplyAction="http://tempuri.org/IRefereeService/GetPlayerResponse")]
        FootballManager.Referee.Presentation.RefereeService.PlayerListItem GetPlayer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRefereeService/GetPlayer", ReplyAction="http://tempuri.org/IRefereeService/GetPlayerResponse")]
        System.Threading.Tasks.Task<FootballManager.Referee.Presentation.RefereeService.PlayerListItem> GetPlayerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRefereeService/GetMatchesList", ReplyAction="http://tempuri.org/IRefereeService/GetMatchesListResponse")]
        FootballManager.Referee.Presentation.RefereeService.MatchListItem[] GetMatchesList(int refereeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRefereeService/GetMatchesList", ReplyAction="http://tempuri.org/IRefereeService/GetMatchesListResponse")]
        System.Threading.Tasks.Task<FootballManager.Referee.Presentation.RefereeService.MatchListItem[]> GetMatchesListAsync(int refereeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRefereeService/GetMatch", ReplyAction="http://tempuri.org/IRefereeService/GetMatchResponse")]
        FootballManager.Referee.Presentation.RefereeService.MatchDTO GetMatch(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRefereeService/GetMatch", ReplyAction="http://tempuri.org/IRefereeService/GetMatchResponse")]
        System.Threading.Tasks.Task<FootballManager.Referee.Presentation.RefereeService.MatchDTO> GetMatchAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRefereeService/SaveGoals", ReplyAction="http://tempuri.org/IRefereeService/SaveGoalsResponse")]
        void SaveGoals(FootballManager.Referee.Presentation.RefereeService.MatchDTO match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRefereeService/SaveGoals", ReplyAction="http://tempuri.org/IRefereeService/SaveGoalsResponse")]
        System.Threading.Tasks.Task SaveGoalsAsync(FootballManager.Referee.Presentation.RefereeService.MatchDTO match);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRefereeServiceChannel : FootballManager.Referee.Presentation.RefereeService.IRefereeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RefereeServiceClient : System.ServiceModel.ClientBase<FootballManager.Referee.Presentation.RefereeService.IRefereeService>, FootballManager.Referee.Presentation.RefereeService.IRefereeService {
        
        public RefereeServiceClient() {
        }
        
        public RefereeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RefereeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RefereeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RefereeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AuthenticateReferee(string username, string password, FootballManager.Domain.Entity.Models.Authentication.Enums.UserType userType) {
            return base.Channel.AuthenticateReferee(username, password, userType);
        }
        
        public System.Threading.Tasks.Task<int> AuthenticateRefereeAsync(string username, string password, FootballManager.Domain.Entity.Models.Authentication.Enums.UserType userType) {
            return base.Channel.AuthenticateRefereeAsync(username, password, userType);
        }
        
        public bool ChangePassword(int userID, string oldPassword, string newPassword) {
            return base.Channel.ChangePassword(userID, oldPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<bool> ChangePasswordAsync(int userID, string oldPassword, string newPassword) {
            return base.Channel.ChangePasswordAsync(userID, oldPassword, newPassword);
        }
        
        public FootballManager.Referee.Presentation.RefereeService.PlayerListItem GetPlayer() {
            return base.Channel.GetPlayer();
        }
        
        public System.Threading.Tasks.Task<FootballManager.Referee.Presentation.RefereeService.PlayerListItem> GetPlayerAsync() {
            return base.Channel.GetPlayerAsync();
        }
        
        public FootballManager.Referee.Presentation.RefereeService.MatchListItem[] GetMatchesList(int refereeId) {
            return base.Channel.GetMatchesList(refereeId);
        }
        
        public System.Threading.Tasks.Task<FootballManager.Referee.Presentation.RefereeService.MatchListItem[]> GetMatchesListAsync(int refereeId) {
            return base.Channel.GetMatchesListAsync(refereeId);
        }
        
        public FootballManager.Referee.Presentation.RefereeService.MatchDTO GetMatch(int id) {
            return base.Channel.GetMatch(id);
        }
        
        public System.Threading.Tasks.Task<FootballManager.Referee.Presentation.RefereeService.MatchDTO> GetMatchAsync(int id) {
            return base.Channel.GetMatchAsync(id);
        }
        
        public void SaveGoals(FootballManager.Referee.Presentation.RefereeService.MatchDTO match) {
            base.Channel.SaveGoals(match);
        }
        
        public System.Threading.Tasks.Task SaveGoalsAsync(FootballManager.Referee.Presentation.RefereeService.MatchDTO match) {
            return base.Channel.SaveGoalsAsync(match);
        }
    }
}
